### ISSUE TITLE
imaplib.error got more than 1000 bytes

### ISSUE THREAD

**Issue by jpaechnatz** [quentinsf/IMAPdedup#12]
Doing a dry run:

Password: 
There are 8801 messages in INBOX/Archiv.
No message(s) currently marked as deleted in INBOX/Archiv
Traceback (most recent call last):
  File "/usr/lib/python3.4/imaplib.py", line 957, in _command_complete
    typ, data = self._get_tagged_response(tag)
  File "/usr/lib/python3.4/imaplib.py", line 1077, in _get_tagged_response
    self._get_response()
  File "/usr/lib/python3.4/imaplib.py", line 985, in _get_response
    resp = self._get_line()
  File "/usr/lib/python3.4/imaplib.py", line 1087, in _get_line
    line = self.readline()
  File "/usr/lib/python3.4/imaplib.py", line 270, in readline
    raise self.error("got more than %d bytes" % _MAXLINE)
imaplib.error: got more than 10000 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/imapdedup", line 271, in <module>
    main()
  File "/usr/bin/imapdedup", line 194, in main
    msgnums = check_response(server.search(None, 'UNDELETED'))[0].split()
  File "/usr/lib/python3.4/imaplib.py", line 660, in search
    typ, dat = self._simple_command(name, *criteria)
  File "/usr/lib/python3.4/imaplib.py", line 1134, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.4/imaplib.py", line 961, in _command_complete
    raise self.error('command: %s => %s' % (name, val))
imaplib.error: command: SEARCH => got more than 10000 bytes

**Comment by quentinsf** [comment]
Mmm. Sorry for not seeing this a year ago!  I wasn't getting notifications, for some reason.

This is really a problem in the underlying IMAP library, on certain servers, with large mailboxes - but I'm not sure how best to deal with it.

I'll have a think about it...

**Comment by quentinsf** [comment]
In the (highly unlikely) case that you're still doing anything with this, I think that adding a line:

    imaplib._MAXLINE = 200000

just after 

    import imaplib

might solve it.  I can't test it here because it doesn't seem to be an issue with my server.

Better late than never!
Q
