### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by jpaechnatz** [quentinsf/IMAPdedup#15]
-c -m causes:

Traceback (most recent call last):
  File "/usr/bin/imapdedup", line 271, in <module>
    main()
  File "/usr/bin/imapdedup", line 216, in main
    msg_id = get_message_id(mp, options.use_checksum, options.use_id_in_checksum)
  File "/usr/bin/imapdedup", line 100, in get_message_id
    md5.update(("Subject:" + parsed_message['Subject']).encode('utf-8'))
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by quentinsf** [comment]
Think this was fixed by the aforementioned patch, so I'm closing the issue.
