### ISSUE TITLE
email.errors.HeaderParseError

### ISSUE THREAD

**Issue by thibaudgg** [quentinsf/IMAPdedup#23]
Hey just got that error when running with the checksum option.

```
There are 72414 messages in Archive.
No message(s) currently marked as deleted in Archive
72414 others in Archive
100 message(s) in Archive processed
200 message(s) in Archive processed
300 message(s) in Archive processed
400 message(s) in Archive processed
Traceback (most recent call last):
  File "./imapdedup.py", line 313, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 310, in main
    process(options, mboxes)
  File "./imapdedup.py", line 249, in process
    msg_id = get_message_id(mp, options.use_checksum, options.use_id_in_checksum)
  File "./imapdedup.py", line 132, in get_message_id
    md5.update("Subject:" + utf8_header(parsed_message,'Subject'))
  File "./imapdedup.py", line 105, in utf8_header
    text, encoding = decode_header(parsed_message.get(name,''))[0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/header.py", line 108, in decode_header
    raise HeaderParseError
email.errors.HeaderParseError
```

**Comment by quentinsf** [comment]
Hi there - 

If you run it with the -v option, does it give you any more information about the message which caused it to stop?  It would be interesting to know what the raw text of the Subject header was...

Quentin

**Comment by thibaudgg** [comment]
Hi Quentin, 

The `-v` option only give me that `Checking Archive message 487`, nothing else more. 
I'm using the master version.

**Comment by quentinsf** [comment]
Hi there - sorry for the delay...

Can you narrow down which message is causing the problem?  If you can work out roughly which is your 487th-oldest message in that mailbox, you might be able to spot one with an unusual subject line.

Or, you could add, around line 246, a 'print mp' command, so it would look like this:

                    if options.verbose:
                        print mp
                        print("Checking %s message %s" % (mbox, mnum))

Then run the script with -v and it should print out each message as it processes them - hopefully you can then see the one causing the problem.

**Comment by thibaudgg** [comment]
Hi @quentinsf, here the printed mail, the subject has some UTF-8 chars `Subject: L'aliment interdit =?UTF-8?B?w6Ag?=consommer sans
 =?UTF-8?B?bW9kw6lyYXRpb24g?=
`.

```
From nobody Tue Mar 31 08:59:01 2015
Delivered-To: guillaumegentil@gmail.com
Received: by 10.227.59.196 with SMTP id m4csp54412wbh;
 Sun, 20 Oct 2013 07:26:21 -0700 (PDT)
X-Received: by 10.194.193.4 with SMTP id hk4mr9899225wjc.29.1382279181272;
 Sun, 20 Oct 2013 07:26:21 -0700 (PDT)
Return-Path: <thibaud+caf_=guillaumegentil=gmail.com@thibaud.me>
Received: from mail-wi0-x22a.google.com (mail-wi0-x22a.google.com
 [2a00:1450:400c:c05::22a])
 by mx.google.com with ESMTPS id lu10si3215285wjb.74.2013.10.20.07.26.20
 for <guillaumegentil@gmail.com>
 (version=TLSv1 cipher=ECDHE-RSA-RC4-SHA bits=128/128);
 Sun, 20 Oct 2013 07:26:21 -0700 (PDT)
Received-SPF: neutral (google.com: 2a00:1450:400c:c05::22a is neither
 permitted nor denied by best guess record for domain of
 thibaud+caf_=guillaumegentil=gmail.com@thibaud.me)
 client-ip=2a00:1450:400c:c05::22a; 
Authentication-Results: mx.google.com;
 spf=neutral (google.com: 2a00:1450:400c:c05::22a is neither permitted nor
 denied by best guess record for domain of
 thibaud+caf_=guillaumegentil=gmail.com@thibaud.me)
 smtp.mail=thibaud+caf_=guillaumegentil=gmail.com@thibaud.me; 
 dkim=pass header.i=@sante-nature-innovation.fr;
 dmarc=pass (p=NONE dis=NONE) header.from=sante-nature-innovation.fr
Received: by mail-wi0-f170.google.com with SMTP id l12so4148080wiv.5
 for <guillaumegentil@gmail.com>; Sun, 20 Oct 2013 07:26:20 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
 d=1e100.net; s=20130820;
 h=x-gm-message-state:delivered-to:dkim-signature:list-unsubscribe
 :date:message-id:to:from:subject:reply-to:mime-version:content-type;
 bh=dDumOu1AbL4qIiEHgVJTvp7t34kbbhMP8ax0mWkVnNk=;
 b=a6j0PGWubn3XzGsxsjTIzMWweCOke7QXguk+AfYYhoCctSvH6i16exLXLW1VecYHm1
 42rdyCpzlp9XqXJjGSgeRx7ur43ds+CaG1H2JMY3lVl3fYip6lg5paLshBbmixQYxBVt
 q6kv8FkpTe8CwSJyaYPp3tqEZW9zoV0eitq3dvFFDstc8N4O++nQ3k6p4q3uYY61mrrq
 mJGgz5MTZQPJhow7bJgPV1Ca7OOZAmjR9WRtthXGlLqwp17xkwtN14L7MYuowdMCkR1H
 n2IJ1J6jwWMyarnNmB2rDqc7wrsqOukGzy9OJygXURFiD/1s4luMBL1Kg361/Q6JmGSF
 /EwA==
X-Gm-Message-State: ALoCoQmkhgODAV475dLK4mAkJp5fBxdE72uB1VxCqZOHkahg+bgNJuR2o2bRWsNzVpO9i19ADXUX
X-Received: by 10.180.182.82 with SMTP id ec18mr6251709wic.13.1382279180741;
 Sun, 20 Oct 2013 07:26:20 -0700 (PDT)
X-Forwarded-To: guillaumegentil@gmail.com
X-Forwarded-For: thibaud@thibaud.me guillaumegentil@gmail.com
Delivered-To: thibaud@thibaud.me
Received: by 10.227.35.197 with SMTP id q5csp49644wbd;
 Sun, 20 Oct 2013 07:26:19 -0700 (PDT)
X-Received: by 10.224.161.146 with SMTP id r18mr17310027qax.57.1382279179020; 
 Sun, 20 Oct 2013 07:26:19 -0700 (PDT)
Return-Path: <bounces-mc-11-81c-945-138-1e9d31-15220@todaysfinancialnews.net>
Received: from mail.todaysfinancialnews.net (mail.todaysfinancialnews.net.
 [208.250.48.92])
 by mx.google.com with ESMTP id u3si5680712qej.89.2013.10.20.07.26.18
 for <THIBAUD@thibaud.me>; Sun, 20 Oct 2013 07:26:18 -0700 (PDT)
Received-SPF: pass (google.com: domain of
 bounces-mc-11-81c-945-138-1e9d31-15220@todaysfinancialnews.net designates
 208.250.48.92 as permitted sender) client-ip=208.250.48.92; 
Return-Path: <bounces-mc-11-81c-945-138-1e9d31-15220@todaysfinancialnews.net>
DKIM-Signature: v=1; a=rsa-sha256; d=sante-nature-innovation.fr; s=dkim1024;
 c=relaxed/simple; 
 q=dns/txt; i=@sante-nature-innovation.fr; t=1382279170;
 h=From:Subject:Date:To:MIME-Version:Content-Type;
 bh=IpEP7yqm1DRfg5rIC8HekOPZ5EwOsQ4mqiDMVC0rIC8=;
 b=evlB7dhmv79kawDPNPNUYvU2v6NGsxpyNRtmVTCgAu9kpTUlicHj3y5oPV7WomyI
 POQ/+fF6f/Rxp027zcvzwGT/M4BwPcUjYaZLo+oYzRxm/6pOTqUeWXfSNSyVgAls
 ImlD9rJ6B9Uyi7Pwj+iqGRBjX16njAYOowRWPS2nrYo=;
X-MSFBL: VEhJQkFVREB0aGliYXVkLm1lQGZyYW5jZS1oZWFsdGhAZGVmYXVsdEA=
List-Unsubscribe: <mailto:unsubscribe-mc-11-81c-945-138-1e9d31-15220@todaysfinancialnews.net>
Received: from [172.16.9.202] ([172.16.9.202:55275] helo=gonzo)
 by prs (envelope-from
 <bounces-mc-11-81c-945-138-1e9d31-15220@todaysfinancialnews.net>)
 (ecelerity 3.4.1.33768 r(MessageSystems/Momo-dev:4870f92e9d2c)) with ESMTP
 id 0A/CE-27320-208E3625; Sun, 20 Oct 2013 10:26:10 -0400
Date: Sun, 20 Oct 2013 10:26:10 -0400
Message-ID: <0A.CE.27320.208E3625@prs>
To: =?ascii?B?VEhJQkFVRCBHVUlMTEFVTUUtR0VOVElM?= <THIBAUD@thibaud.me>
From: "Sante Nature Innovation" <santenutrition@sante-nature-innovation.fr>
X-rpcampaign: agoraSF1_002076000312
X-Binding: FRANCE-HEALTH
Subject: L'aliment interdit =?UTF-8?B?w6Ag?=consommer sans
 =?UTF-8?B?bW9kw6lyYXRpb24g?=
Reply-To: 
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="-----=526115fa07c5b"
```

**Comment by meyer** [comment]
I’m running into this issue as well. Here’s the header that’s causing the issue for me:

```=?iso-2022-jp?B?GyRCIXobKEIgRmlyc3QgMTAlIGNvdXBvbiBvbiBjbGVhcmFuY2UgaXRl?==?iso-2022-jp?B?bXM=?=```

**Comment by quentinsf** [comment]
I'm closing this as I'm doing some rewriting and I hope this won't be an issue in the new version!
