### ISSUE TITLE
Attempting to process the inbox.

### ISSUE THREAD

**Issue by hydroflash** [quentinsf/IMAPdedup#32]
I can perform a dry run but then I change the -n option to -P I get the following:

imapdedup.py -s <server> -u <password> -x -P INBOX
/bin/sh: INBOX: command not found
Traceback (most recent call last):
  File "/Users/ccoles/Desktop/IMAPdedup-master/imapdedup.py", line 313, in <module>
    main(sys.argv[1:])
  File "/Users/ccoles/Desktop/IMAPdedup-master/imapdedup.py", line 310, in main
    process(options, mboxes)
  File "/Users/ccoles/Desktop/IMAPdedup-master/imapdedup.py", line 171, in process
    server = serverclass(options.process)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 1241, in __init__
    IMAP4.__init__(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 194, in __init__
    self.welcome = self._get_response()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 929, in _get_response
    resp = self._get_line()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/imaplib.py", line 1029, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF

**Comment by quentinsf** [comment]
Hi there - 

Are you actually using a separate process, which needs the '-P' option?

That's a pretty special case; most people would just remove the '-n' to talk to a remote IMAP server...

All the best, 
Quentin

**Comment by hydroflash** [comment]
I must admit that I do not have a strong understanding of how to properly syntax commands.  I did figure it out and cleansed over 25000 duplicates.  Thank you for response and hard work on the script.

**Comment by quentinsf** [comment]
Great!
