### ISSUE TITLE
Error using -P with wrapper: /bin/sh: 1: local: not in a function

### ISSUE THREAD

**Issue by warwickchapman** [quentinsf/IMAPdedup#44]
I'm not sure how the wrapper script for -P is supposed to work.  I am using this on Mail-in-a-Box (Dovecot) with a script called 'local':

`#!/bin/bash
/usr/lib/dovecot/imap -o mail_location=maildir:/home/user-data/mail/mailboxes/domain.com/test`

Error I get is:
`# ./imapdedup.py -s localhost -u test@domain.com -x -v INBOX -P local
/bin/sh: 1: local: not in a function
Traceback (most recent call last):
  File "./imapdedup.py", line 324, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 321, in main
    process(options, mboxes)
  File "./imapdedup.py", line 182, in process
    server = serverclass(options.process)
  File "/usr/lib/python2.7/imaplib.py", line 1240, in __init__
    IMAP4.__init__(self)
  File "/usr/lib/python2.7/imaplib.py", line 193, in __init__
    self.welcome = self._get_response()
  File "/usr/lib/python2.7/imaplib.py", line 928, in _get_response
    resp = self._get_line()
  File "/usr/lib/python2.7/imaplib.py", line 1028, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF`

**Comment by quentinsf** [comment]
Well, two years later, I get around to replying - sorry!

I think you had an issue because you called the script 'local' - that's a bash builtin command.

Apologies for not responding at the time.
