### ISSUE TITLE
Too many values to unpack 

### ISSUE THREAD

**Issue by koalacurioso** [quentinsf/IMAPdedup#57]
I got this error, any clue ? 

`21200 message(s) in Sent processed
Traceback (most recent call last):
  File "./imapdedup.py", line 536, in <module>
    main(sys.argv[1:])
  File "./imapdedup.py", line 532, in main
    process(options, mboxes)
  File "./imapdedup.py", line 440, in process
    for mnum, hinfo in get_msg_headers(server, msgnums[i: i + chunkSize]):
  File "./imapdedup.py", line 316, in get_msg_headers
    _, hinfo = ms[ci * 2]
ValueError: too many values to unpack (expected 2)`

**Comment by diegorusso** [comment]
I have the same.

**Comment by ajdelgado** [comment]
+1

**Comment by echodreamz** [comment]
+1

**Comment by quentinsf** [comment]
I think this should be fixed in v1.3.  But it only happens on certain not-quite-conformant servers so I can't test it - feel free to re-open if it still occurs.
